### ISSUE TITLE
Add support for Spring-boot 3

### ISSUE THREAD

**Issue by cloudpay-simon** [throwable/mdc4spring#3]
Auto configuration for Spring-boot 3 doesn't work because the name of the registration file (under META-INF) has changed.

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration
and https://github.com/spring-projects/spring-boot/issues/33413

A workaround it to import the auto configuration classes explicitly by adding the following line to one of your configuration classes.
`@ImportAutoConfiguration(MDCAutoConfiguration.class)`

Thank you so much for your library.
Simon

**Comment by throwable** [comment]
Thanx for your report. Fixed in v1.1 (see [changelog](https://github.com/throwable/mdc4spring/blob/master/CHANGELOG.md)).
